### PR TITLE
Added new field disableCampaignParameters

### PR DESCRIPTION
**Pull request by AltamashShaikh**
### Description:

Added new field disableCampaignParameters

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by AltamashShaikh** [comment]
[Internal](https://innocraft.atlassian.net/wiki/spaces/DP/pages/1976532993/How+to+make+changes+in+Matomo+Template+for+Google+Tag+Manager) document to test this.

**Comment by AltamashShaikh** [comment]
Getting an error for cloud domain as the change is not live yet, but works fine for local domain

Screenshot from 2024-03-27 07-00-53

Screenshot from 2024-03-27 07-02-54

**Review by snake14 — APPROVED** [review]
Looks good and it appeared to be working when I tried using it in GTM.

**Review by snake14 — APPROVED** [review]
Looks good to me :+1:

**Pull request merged**
